#!/bin/sh
### BEGIN INIT INFO
# Provides:          aria2
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Aria2 Downloader
### END INIT INFO

USER=pi
CONF=/home/pi/.aria2/aria2.conf

case "$1" in
start)
    echo "Start aria2c"
    umask 0002
    su - $USER -c "aria2c --conf-path=$CONF -D"
    ;;
stop)
    echo "Stopping aria2c, please wait..."
    killall -w aria2c
    ;;
restart)
    echo "Stopping aria2c, please wait..."
    killall -w aria2c
    echo "Start aria2c"
    umask 0002
    su - $USER -c "aria2c --conf-path=$CONF -D"
    ;;
*)
    echo "$0 {start|stop|restart|status}"
    ;;
esac
exit
