#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpc_control_aria2c
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rpc_control_aria2c Downloader
### END INIT INFO

USER=pi
case "$1" in
start)
    echo "Start rpc_control_aria2c"
    umask 0002
    su - $USER -c "/usr/bin/python /home/pi/rpc_control_aria2c.py"
    ;;
stop)
    echo "Stopping rpc_control_aria2c, please wait..."
    killall -w rpc_control_aria2c.py
    ;;
restart)
    echo "Stopping rpc_control_aria2c, please wait..."
    killall -w rpc_control_aria2c.py
    echo "Start rpc_control_aria2c"
    umask 0002
    su - $USER -c "/usr/bin/python /home/pi/rpc_control_aria2c.py"
    ;;
*)
    echo "$0 {start|stop|restart|status}"
    ;;
esac
exit
